// <auto-generated />
namespace LabManagementWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addUserFieldsToBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserFieldsToBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030039179_addUserFieldsToBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
